# site settings
title: MasterKtos
subtitle: Portfolio
email: sledzikowska.m@gmail.com
formspree_code: mgebdaaw
description: I am an aspiring game developer, huge guinea pig fan and occasional yerba mate enjoyer
baseurl: # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 
city: Bydgoszcz | Łódź
state: 
zip_code: 
country: Poland
phone:

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/masterktos
  Itch-io: https://masterktos.itch.io
  LinkedIn: https://www.linkedin.com/in/michalina-śledzikowska-a0848826a/

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
