title: MasterKtos | Portfolio
description: Hobbyist game developer, 3D modeler & occasional yerba enjoyer

# Variables
show_menu: true


remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one



